apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: magento
spec:
  ports:
    - port: 3306
  selector:
    app: db
  clusterIP: None
---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: magento-mariadb
# spec:
#   capacity:
#     storage: 5Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Recycle
#   nfs:
#     path: /var/nfs/general/magento/mariadb
#     server: 65.21.238.216
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: magento-mariadb
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento-mariadb
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: docker.io/bitnami/mariadb:10.4
        name: mariadb
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 500Mi
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MARIADB_USER
          value: bn_magento
        - name: MARIADB_PASSWORD
          value: mypassword
        - name: MARIADB_ROOT_PASSWORD
          value: mypassword
        - name: MARIADB_DATABASE
          value: bitnami_magento
        ports:
        - containerPort: 3306
          name: mariadb
      #   volumeMounts:
      #   - name: mariadb-data
      #     mountPath: /bitnami/mariadb
      # volumes:
      # - name: mariadb-data
      #   persistentVolumeClaim:
      #     claimName: magento-mariadb